@startuml

autonumber
Title Login Sequence GET
actor customer

boundary Tomcat

customer -> Tomcat:GET /


box entries (UI)
Tomcat -> Index:doGet()
Index -> BaseServlet:render()
BaseServlet -> index.jsp:forward()

index.jsp -> Login:doGet()

Login -> BaseServlet:render()

BaseServlet -> login.jsp:forward()
end box

login.jsp --> customer:result

@enduml