@startuml

autonumber
Title Login Sekvensdiagram POST
actor customer

boundary Tomcat

customer -> Tomcat:POST /Login

box web (UI)
Tomcat -> Login: doPost()
end box



box api (logic)
Login -> api:login(email, password)
end box

'box domain (interface)
'api -> userServices:login(email)
'end box

box infrastructure
api -> DBUser:login(email)
database DB
DBUser -> DB:executeQuery()
end box





DB --> DBUser:result (User)
DBUser --> api:result
'DBUserServices --> userServices:result
'userServices --> api:result
api -> api: validate User
api -> api: validate Password
api --> Login: result
Login --> customer: Redirect




@enduml