@startuml
Title Activity Diagram

|Customer|
start
:Go to website;

|#AntiqueWhite|Website|
:Choose product;
:View cart;
:Login or Register;
:Checkout;
:Choose delivery;
:Choose Payment;
:Thank you for your order message;
|Shop|
:Receive order;
:Prepare order;
    if (Shipping_option) equals (no) then
    |Shop|
    :Pick up order;
    stop

    else (yes)
    |#AntiqueWhite|Shipment|
    :Ship order;
    |Customer|
    :receive order;
    stop


|#AntiqueWhite|Website|
start
:Update order;
stop

@enduml