@startuml
Title Aktivitetsdiagram TO-BE

|Kunde|
start
:Besøger hjemmeside;

|#AntiqueWhite|Hjemmeside|
:Indsender specifikation;

|Sælger|
:Modtager bestilling;
:Sælger kontakter kunde;

|#AntiqueWhite|Hjemmeside|
:Udregner tilbud;

|Sælger|
:Retter i tilbud;
:Sender tilbud til kunden;

|Kunde|
:Overvejer tilbud;
    if (Tilfreds med tilbudet) equals (nej) then
'    |Sælger|
'    :Afviser tilbud;
'
'    |Sælger|
'    :Sælger får afvisning og opsøger
'    kunden på ny mht. et evt. ny tilbud;
    stop

    else (ja)
    |Sælger|
    :Bestiller tilbud;
    :Sælger klargører bestilling;

    |Lager|
    :Bestilling klargøres;

    |Sælger|
    :Sælger kontakter kunde;

    |Lager|
    :Bestilling afhentes af kunden;

    |Kunde|
    :Bestilling ankommer hos kunde;

    |Sælger|
    :Opdaterer bestilling;
    stop







@enduml