@startuml
Title Use Case
left to right direction

actor customer
actor sælger
actor admin

rectangle hjemmeside {
    customer -- (Vælge carport inkl. specifikationer)
    customer -- (Vælge skur inkl. specifikationer)
    customer -- (Send forespørgsel)


    sælger -- (Login)
    sælger -- (Logout)
    sælger -- (Se forespørgsler)
    (Se forespørgsler) -- (Rette i forespørgsler) : inkl.
    (Se forespørgsler) -- (Se listepriser) : inkl.
    sælger -- (Se listepriser)



    admin -- (Login)
    admin -- (Logout)
    admin -- (Se profiler)
    (Se profiler) -- (Oprette profiler) : inkl.
    (Se profiler) -- (Ændre profiler) : inkl.
    (Se profiler) -- (Slette profiler) : inkl.
    admin -- (Se forespørgsler)
    admin -- (Se listepriser)
    (Se listepriser) -- (Tilføj listepriser) : inkl.
    (Se listepriser) -- (Ændre listepriser) : inkl. (admin)
    (Se listepriser) -- (Slet listepriser) : inkl. (admin)
}

@enduml