@startuml
Title Use Case
left to right direction

actor kunde
actor sælger
actor admin

rectangle hjemmeside {
    kunde -- (Vælge carport m/u skur)
    (Vælge carport m/u skur) -- (Send forespørgsel):inkl.
    (Send forespørgsel) -- (Se forespørgsel): inkl.
    kunde -- (Se bestillling)


    sælger -- (Login)
    sælger -- (Logout)
    sælger -- (Se forespørgsler)
    (Se forespørgsler) -- (Ret forespørgsel) : inkl.
    (Se forespørgsler) -- (Se listepriser) : inkl.
    sælger -- (Se kunder)

    admin -- (Login)
    admin -- (Logout)
    admin -- (Se sælgere)
    (Se sælgere) -- (Opret sælger) : inkl.
    (Se sælgere) -- (Slet sælger) : inkl.
    admin -- (Se forespørgsler)
    admin -- (Se listepriser)
    (Se listepriser) -- (Ændre listepriser) : inkl. (admin)

}

@enduml