@startuml
Title Use Case
left to right direction

actor kunde
actor sælger
actor admin

rectangle hjemmeside {
    kunde -- (Vælge carport m/u skur efter specifikationer)
    kunde -- (Send forespørgsel)
    kunde -- (Se forespørgsel)


    sælger -- (Login)
    sælger -- (Logout)
    sælger -- (Se forespørgsler)
    (Se forespørgsler) -- (Rette i forespørgsler) : inkl.
    (Se forespørgsler) -- (Se listepriser) : inkl.
    (Se forespørgsler) -- (Vælge forespørgsler) : inkl.
    sælger -- (Se kunder)

    admin -- (Login)
    admin -- (Logout)
    admin -- (Se sælgere)
    (Se sælgere) -- (Opret sælger) : inkl.
    (Se sælgere) -- (Ændre sælger) : inkl.
    (Se sælgere) -- (Slet sælger) : inkl.
    admin -- (Se forespørgsler)
    admin -- (Se listepriser)
    (Se listepriser) -- (Ændre listepriser) : inkl. (admin)

}

@enduml