@startuml
Title Use Case
left to right direction

actor kunde
actor sælger
actor admin

rectangle hjemmeside {
    kunde --> (Vælge carport m/u skur)
    (Vælge carport m/u skur) ..> (Send forespørgsel):<<includes>>
    (Send forespørgsel) ..> (Se forespørgsel):<<includes>>
    kunde --> (Se bestillling)


    sælger --> (Login)
    sælger --> (Logout)
    sælger --> (Se forespørgsler)
    (Se forespørgsler) ..> (Ret forespørgsel):<<includes>>
    (Se forespørgsler) ..> (Se listepriser):<<includes>>
    sælger --> (Se kunder)

    admin --> (Login)
    admin --> (Logout)
    admin --> (Se sælgere)
    (Se sælgere) ..> (Opret sælger):<<includes>>
    (Se sælgere) ..> (Slet sælger):<<includes>>
    admin --> (Se forespørgsler)
    admin --> (Se listepriser)
    (Se listepriser) ..> (Ret listepriser):<<includes>> (admin)

}

@enduml