@startuml
Title Aktivitetsdiagram AS-IS


|Kunde|
start
repeat
:Beskriver behov og opretter behov;

|#AntiqueWhite|IT System|
:Visualiser carport og kundes behov;

|Kunde|
:Vurdere billede;
repeat while (accept) is (no)
:Bestil carport;

|#AntiqueWhite|IT System|
:Tilføj bestilling til liste;
:Beregner tilbud m. stykliste;


|Sælger|
:Se bestilling på liste;
repeat

|Sælger|
:Gennemgår tilbud;
:Kontakter kunde på tlf.;
:Sender tilbud til kunden via mail,
med tilbud som PDF;

|Kunde|
:Vurdere tilbud;

repeat while (accept) is (no)


|Sælger|
:Opretter ordre;
:Sender faktura til kunde vi mail,
med bestilling som PDF;

|Kunde|
if (Betaler for bestilling) then
:Afhenter materialer på lager
og bygger carport;
stop

else
|Sælger|
:Opdaterer bestilling;
:Følger op med kunde;
stop

@enduml