@startuml
Title Aktivitetsdiagram AS-IS


|Kunde|
start
:Besøger hjemmeside;

|#AntiqueWhite|Hjemmeside|
:Indsender specifikation;

|Sælger|
:Modtager order;
:Sælger kontakter customer;

|#AntiqueWhite|Hjemmeside|
:Udregner tilbud;

|Sælger|
:Sender tilbud til kunden;

|Kunde|
:Overvejer tilbud;
    if (Tilfreds med tilbudet) equals (nej) then
    stop

    else (ja)
    |Sælger|
    :Bestiller tilbud;
    :Sælger klargører order;

    |Lager|
    :Bestilling klargøres;

    |Sælger|
    :Sælger kontakter customer;

    |Lager|
    :Bestilling afhentes af kunden;

    |Kunde|
    :Bestilling ankommer hos customer;

    |Sælger|
    :Opdaterer order;
    stop



@enduml