@startuml
Title Navigationsdiagram

state index.jsp
state login.jsp


note top of login.jsp
User objekt gemmes
i en session
end note


[*] --> index.jsp: Start bestilling
[*] --> email: Se bestilling
index.jsp -right-> carport.jsp
index.jsp -left-> login.jsp


login.jsp --> login.jsp:error


carport.jsp --> confimation.jsp
confimation.jsp --> thankyou.jsp

state kundeOmråde {
        email ----> vieworder: Link via email
        thankyou.jsp --> vieworder
    }



state LoggetInd {


    state adminOmråde{

        login.jsp --> orders
        orders --> customers
        orders --> vieworder:Adgang via link
        orders --> materials.jsp
        materials.jsp --> editmaterial.jsp
        orders --> users.jsp
        orders --> logout

    }

    state salesOmråde{

            login.jsp --> orders.jsp
            orders.jsp --> customers.jsp
            orders.jsp --> vieworder:Adgang via link
            orders.jsp --> logout.jsp
        }

}




@enduml