@startuml
Title Navigationsdiagram







state "/" as index

[*] --> index: Ny kunde

state "Login/" as login :Login

state "loggedInd" as l {

  state "EmployeeOmråde" as u {


      state "Orders/" as u_orders :Se alle ordre
      state "ViewOrder/{id}" as u_order_details :Se aktuel ordre

      login --> u_orders
      u_orders --> u_order_details

  }

  state "adminOmråde" as a {


      state "Orders/" as a_orders :Se alle ordre
      state "ViewOrder/{id}" as a_order_details :Se aktuel ordre

      state "Customers/" as a_customer :Se alle kunder

      state "Users/" as a_users :Se, opret og slet ansatte

      state "Materials/" as a_materials :Se og ret i materialer

      login --> a_orders
      a_orders --> a_order_details

      a_orders --> a_customer

      a_orders --> a_users

      a_orders --> a_materials
  }

}


'state "customerNew" as cn {

    state "Shop/" as cn_shop :Bestil carport
    state "Confirmation/" as cn_confirmation :Bekræft bestilling
    state "Confirmation/" as cn_thankyou :Ordre bekræftelse
    state "ViewOrder/{id}" as cn_vieworder :Se ordre

    index -right-> cn_shop
    cn_shop --> cn_confirmation
    cn_confirmation --> cn_thankyou
    cn_thankyou --> cn_vieworder

    [*] -down-> cn_vieworder:Kunde ordre link
'}
'
'state "customerReturn" as co {
'
'    state "ViewOrder/{id}" as co_vieworder :Se ordre
'
'    [*] --> co_vieworder
'}

index -down-> login
'index -down-> cn
'index -down-> co

@enduml