/*
 * Copyright (c) 2020. Team CoderGram
 *
 * @author Emil Elkjær Nielsen (cph-en93@cphbusiness.dk)
 * @author Sigurd Arik Twena Nielsen (cph-at89@cphbusiness.dk)
 * @author Jacob Lange Nielsen (cph-jn352@cphbusiness.dk)
 */

package selenium; // Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

public class AdminloginandlogoutTest {
  private final static String OS = System.getProperty("os.name").toLowerCase();
  private WebDriver driver;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    String path = "src/test/resources/geckodriver";

    if(OS.contains("win")) path += ".exe";

    File file = new File(path);
    System.setProperty("webdriver.gecko.driver", file.getAbsolutePath());

    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void adminloginandlogout() {
    driver.get("http://localhost:8080//fog");
    driver.manage().window().setSize(new Dimension(924, 1012));
    driver.findElement(By.linkText("Log ind")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("admin@admin.dk");
    driver.findElement(By.id("inputPassword")).sendKeys("admin");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.linkText("Ansatte")).getText(), is("Ansatte"));
    driver.findElement(By.linkText("Log ud")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Log ind"));
      assert (elements.size() > 0);
    }
  }
}
