@startuml
Title Domænemodel (Carport)

hide circle
hide methods

class Carport {
    længde
    bredde
}

class Tag {
    højde
    bredde
    længde
    type
}

class Tagbeklædning {

}

class TagMontering {

}

class Spær {
    længde
}

class Rem {
    længde
}

class Stern {
    længde
}

class Lægte {
    længde
}

class Fundament {

}

class Bolt {
   længde
   bredde
}

class Skive {
   længde
   højde
   bredde
}

class Stolpe {
   højde
}

class Skur {

}

class Skur {
    længde
    bredde
}

class Dør {
    Bredde
}


class Greb {
    længde
    bredde
}

class Beklædning {
    længde
}

class Hjørne {

}

class SkurMontering {

}

class Tagsten {
   længde
   bredde
}

class Tagplade {
   længde
   bredde
}

class Skrue {
    længde
    bredde
}

class Universal {
    længde
}

class Beslag {
    type
}

class Hængsel {
    længde
}

Carport "1" -- "1" Tag: har et
Tag "1" -- "*" Tagbeklædning: har en
Tagbeklædning "1" -- "0..400" Tagsten: er en
Tagbeklædning "1" -- "0..6" Tagplade: er en


Tag "1" -- "*" TagMontering: inkl.
TagMontering "1" -- "1000" Skrue: er en
TagMontering "1" -- "3" Universal: er en
TagMontering "1" -- "15..30" Lægte: er en



Tag "1" -- "8..18" Spær: er et
Tag "1" -- "2" Rem: er en
Tag "1" -- "2" Stern: er en



Carport "1" -- "1" Fundament: har et
Fundament "1" -- "6" Stolpe: er en
Fundament "1" -- "2" Bolt: er en
Fundament "1" -- "1" Skive: er en


Carport "1" -- "0..1" Skur: kan have et
Skur "1" -- "1" Dør: har en
Skur "1" -- "100..250" Beklædning: har en
Skur "1" -- "*" SkurMontering: inkl.
SkurMontering "1" -- "700" Skrue: er en
Skur "1" -- "2..3" Hjørne: har et
Hjørne "1" -- "1" Stolpe: er en
Dør "1" -- "1" Greb: er et
Dør "1" -- "32" Beslag: er et
Dør "1" -- "2" Hængsel: er et
Dør "1" -- "1" Lægte: er en


@enduml