@startuml
Title Domænemodel (Carport)

hide circle
hide methods

class Carport {
    længde
    bredde
}

class Tag {
    højde
    bredde
    længde
    type
}

class Tagbeklædning {
  type
}

class TagMontering {

}

class Spær {
    længde
}

class Rem {
    længde
}

class Stern {
    længde
}

class Lægte {
    længde
}

class Fundament {

}

class Bolt {
   længde
   bredde
}

class Skive {
   længde
   højde
   bredde
}

class Stolpe {
   højde
}

class Skur {

}

class Skur {
    længde
    bredde
}

class Dør {
    Bredde
}


class Greb {
    længde
    bredde
}

class Beklædning {
    længde
}

class Hjørne {

}

class SkurMontering {

}

class Tagsten {
   længde
   bredde
}

class Tagplade {
   længde
   bredde
}

class Skrue {
    længde
    bredde
}

class Universal {
    længde
}

class Beslag {
    type
}

class Hængsel {
    længde
}

Carport "1" -- "1" Tag
Tag "1" -- "*" Tagbeklædning
Tagbeklædning "1" -- "0..*" Tagsten
Tagbeklædning "1" -- "0..6" Tagplade


Tag "1" -- "*" TagMontering
TagMontering "1" -- "*" Skrue
TagMontering "1" -- "3" Universal
TagMontering "1" -- "15..30" Lægte



Tag "1" -- "8..18" Spær
Tag "1" -- "2" Rem
Tag "1" -- "2" Stern



Carport "1" -- "1" Fundament
Fundament "1" -- "6" Stolpe
Fundament "1" -- "2" Bolt
Fundament "1" -- "1" Skive


Carport "1" -- "0..1" Skur
Skur "1" -- "1" Dør
Skur "1" -- "*" Beklædning
Skur "1" -- "*" SkurMontering
SkurMontering "1" -- "*" Skrue
Skur "1" -- "2..3" Hjørne
Hjørne "1" -- "1" Stolpe
Dør "1" -- "1" Greb
Dør "1" -- "32" Beslag
Dør "1" -- "2" Hængsel
Dør "1" -- "1" Lægte


@enduml